name: kymble
favicon: null
layout_spectrum: 0.1786978212185204
typography_spectrum: 0.9866229526232928
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7724541951902211
  lightness: 0.46702439594082534
  saturation: 0.41179104056209326
  rhythmicContrast: 0.6830858672037721
purpose: []
