name: kymble
favicon: null
layout_spectrum: 0.40515
typography_spectrum: 0.9866229526232928
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#293659'
    - '#989397'
    - '#540a05'
  brandStrength: 0.75
  lightness: 0.46702439594082534
  saturation: 0.41179104056209326
  rhythmicContrast: 0.6830858672037721
purpose: []
